# Generated by Django 4.1.6 on 2023-02-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product_transaction_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
