# Generated by Django 4.1.6 on 2023-02-10 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_product_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_ref',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='name',
        ),
    ]
