# Generated by Django 4.1.6 on 2023-02-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_transaction_cart_transaction_id_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='cart',
        ),
        migrations.AddField(
            model_name='transaction',
            name='bought',
            field=models.ManyToManyField(to='api.product'),
        ),
    ]
