# Generated by Django 4.1.6 on 2023-02-10 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_transaction_cart_transaction_bought'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='bought',
        ),
        migrations.AddField(
            model_name='transaction',
            name='bought',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.product'),
        ),
    ]
