# Generated by Django 4.1.6 on 2023-02-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_transaction_bought_transaction_bought'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='products',
            field=models.ManyToManyField(default=0, to='api.product'),
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='bought',
        ),
        migrations.AddField(
            model_name='transaction',
            name='bought',
            field=models.ManyToManyField(default=0, to='api.product'),
        ),
    ]
